Fixed load, save and resume in trainer and corresponding tests.

diff --git a/make_spec b/make_spec
--- a/make_spec
+++ b/make_spec
@@ -4,8 +4,8 @@ if [ ! -d openapi ]
 then mkdir openapi
 fi
 
-python -W ignore -m dorc.spec -t [_%C%r%n]_%h --gen-opid --no-interface --excludes '/trainer/.*' -df openapi/daemon.yml
-python -W ignore -m dorc.spec  -t [_%C%r%n]_%h --gen-opid --no-daemon -if openapi/iface.yml
+python -W ignore -m dorc generate_spec -t [_%C%r%n]_%h --gen-opid --no-interface --excludes '/trainer/.*' -df openapi/daemon.yml
+python -W ignore -m dorc generate_spec  -t [_%C%r%n]_%h --gen-opid --no-daemon -if openapi/iface.yml
 
 openapi-spec-validator openapi/daemon.yml
 if [ $? -eq 0 ]
@@ -13,8 +13,8 @@ then echo "Validated interface spec"
      # java -jar swagger-codegen-cli.jar generate --lang javascript -o openapi/iface -i openapi/iface.yml
      java -jar openapi-generator-cli-5.0.0.jar generate -g javascript-flowtyped -o openapi/iface -i openapi/iface.yml -t out
      echo "Generated interface client API"
-else echo "Failed for interface"
-     return 1
+else echo "Validation failed for interface"
+     exit 1
 fi
 
 openapi-spec-validator openapi/iface.yml
@@ -23,6 +23,6 @@ then echo "Validated daemon spec"
      # java -jar swagger-codegen-cli.jar generate --lang javascript -o openapi/daemon -i openapi/daemon.yml
      java -jar openapi-generator-cli-5.0.0.jar generate -g javascript-flowtyped -o openapi/daemon -i openapi/daemon.yml -t out
      echo "Generating daemon client API"
-else echo "Failed for daemon"
-     return 1
+else echo "Validation failed for daemon"
+     exit 1
 fi
